<?php  if(!empty($this->pages)):?>
<ul class="breadcrumb">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            // if this isn't the last page, add a link and the separator
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo ucwords($page->getLabel()); ?></a>
                <span class="divider">/</span>
            <?php // otherwise, just output the name
            else:
            ?>
                <?php echo ucwords($page->getLabel()); ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
</ul>
<?php  endif; ?>