<?
if (! $this->ZfcUserIdentity ()) :
	echo $this->zfcUserLoginWidget ();
	die ();
							
endif;
?>
<?php
//doctype
echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('University of Nevada Las Vegas | ' . $this->translate('Enterprise Application Services'))->setSeparator(' | ')->setAutoEscape(true) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon/faviconred.ico'))
                ->prependStylesheet($this->basePath() . '/css-uni/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css-uni/style.css')
                ->prependStylesheet($this->basePath() . '/css-uni/select2.css')                                     
                ->prependStylesheet($this->basePath() . '/css-uni/bootstrap.min.css')                
                ->prependStylesheet($this->basePath() . '/css-uni/social-style.css')
                ->prependStylesheet($this->basePath() . '/css-uni/font-awesome.min.css')
        ?>
        
        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js-uni/html5.js', 'text/javascript', array(
                    'conditional' => 'lt IE 9'))
                ->prependFile($this->basePath() . '/js-uni/jquery-1.7.2.min.js')
                ->appendFile($this->basePath() . '/js-uni/jqueryUI/ui/jquery-ui-1.8.24.custom.js') 
                ->appendFile($this->basePath() . '/js-uni/ajaxform.js');
        ?>
    </head>
    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                    </a>
                    
                    <a class="brand" href="http://www.unlv.edu">                        
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation('header-navigation')->menu()                                                                    
                                                                    ->setUlClass('nav navbar-nav')
                                                                    ->setMaxDepth(1)
                                                                    ->setPartial(array('partial/header-navigation.phtml', 'Application')); 
                        ?>
                        <div class="dropdown login-button">
                            <? if (!$this->zfcUserIdentity()): ?>                        
                                <a href="<?php echo $this->url('zfcuser/login') ?>" role="button">
                                    <button class="btn">Login</button>
                                </a>                  
                            <? else: ?>

                               <div class="user-thumb"><?= $this->zfcUserDisplayName() ?></div>                        
                                <a class="user-thumb user-thumb-link" data-toggle="dropdown"><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a tabindex="-1" href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                                    <li><a tabindex="-1" href="<?php echo $this->url('zfcuser/profile') ?>">Profile</a></li>
                                </ul>
                            <? endif; ?>
                        </div>
                    </div> 

                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>                   
        
        <div id="content" class="container"> 
        <? if(isset($this->alert)): ?>        
        <div class="login">
            <div class="alert in alert-block fade alert-alert"><?=ucfirst($this->app) ?> is under maintenance at this time. Please check back later!</div>
        </div>
        <? endif; ?>
        <?        
        if(!$this->ZfcUserIdentity() && !isset($this->alert)) :
            echo  $this->zfcUserLoginWidget(); 
        endif; 
        if($this->ZfcUserIdentity() && !isset($this->alert)): 
            echo $this->navigation('header-navigation')->breadcrumbs()
                                                ->setMinDepth(0)
                                                ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
                                                
            echo $this->content; 
        endif; 
        ?>
        </div>

        <div class='navbar navbar-fixed-bottom'>
            <div class="subnavbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" >
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    
                    <div class="nav-collapse">
                        <ul  class="nav">
                            <li><a href="http://www.unlv.edu">UNLV Website</a></li>                  
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Visit UNLV <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a tabindex="-1" href="http://www.unlv.edu/eventservices/accommodations">Accomodations on Campus</a></li>
                                    <li><a tabindex="-1" href="http://www.unlv.edu/admissions/tours">Campus Tours</a></li>
                                    <li><a tabindex="-1" href="http://www.unlv.edu/maps/addresses-directions">Driving Directions</a></li>
                                    <li><a tabindex="-1" href="http://www.unlv.edu/maps">Maps & Parking</a></li>
                                    <li><a tabindex="-1" href="http://web.unlv.edu/global/images/galleries/Campus/">Photo Gallery</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Contact Us <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a tabindex="-1" href="contact/admissions">Admissions</a></li>
                                    <li><a tabindex="-1" href="contact/registrar">Registrar's Office</a></li>
                                    <li><a tabindex="-1" href="contact/eas">Enterprise Applications Services</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            <footer>
                <div class="container feature">
                    <h1>University of Nevada, Las Vegas</h1>
                    <?php require 'social.phtml'; ?>
                </div>
            </footer>
            <div id='footer'>
                <h4>Designed and Developed by Enterprise Application Services | &copy; 2014 University of Nevada, Las Vegas</h4>
            </div>
        </div>
        <?php echo $this->inlineScript()                               
//                ->prependFile($this->basePath('js/ezsign-javascript.js'))                           
//                ->prependFile($this->basePath('js/unicorn.interface.js'))                 
//                ->prependFile($this->basePath('js/jquery.blockUI.js'))
                //automatically populate the shipping address fields
                ->prependFile($this->basePath('js-uni/shipping-billing.js'))                              
                //->prependFile($this->basePath('js/unicorn.form_common.js'))
                //->prependFile($this->basePath('js/unicorn.js')) 
                ->prependFile($this->basePath('js-uni/select2.min.js'))
                //->prependFile($this->basePath('js/bootstrap-colorpicker.js'))
                //->prependFile($this->basePath('js/bootstrap-datepicker.js'))
                //->prependFile($this->basePath('js/jquery.uniform.js'))
                ->prependFile($this->basePath('js-uni/bootstrap.min.js'))                
                //->prependFile($this->basePath('js/jquery.ui.custom.js'))
                //->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js-uni/phone-input-mask.js'))             
                //->prependFile($this->basePath('js/jquery.wizard.js')) 
                //->prependFile($this->basePath('js/unicorn.wizard.js')) 
        ?>
    </body>
</html>