<div class=''>
    <ul class="social-grid">
        <li>
            <div class="social-item">				
                <div class="social-info-wrap">
                    <div class="social-info">
                        <div class="social-info-front social-small-twitter">
                            <a href="http://www.unlv.edu/directories/socialmedia/twitter"></a>
                        </div>
                        <div class="social-info-back social-small-twitter-hover">
                            <a href="http://www.unlv.edu/directories/socialmedia/twitter"></a>
                        </div>	
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="social-item">				
                <div class="social-info-wrap">
                    <div class="social-info">
                        <div class="social-info-front social-small-facebook">
                            <a href="http://www.unlv.edu/directories/socialmedia/facebook"></a>
                        </div>
                        <div class="social-info-back social-small-facebook-hover">
                            <a href="http://www.unlv.edu/directories/socialmedia/facebook"></a>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="social-item">				
                <div class="social-info-wrap">
                    <div class="social-info">
                        <div class="social-info-front social-small-youtube">
                            <a href="http://www.unlv.edu/directories/socialmedia/youtube"></a>
                        </div>
                        <div class="social-info-back social-small-youtube-hover">
                            <a href="http://www.unlv.edu/directories/socialmedia/youtube"></a>
                        </div>	
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="social-item">				
                <div class="social-info-wrap">
                    <div class="social-info">
                        <div class="social-info-front social-small-rss">
                            <a href="http://www.unlv.edu/directories/socialmedia/rss"></a>
                        </div>
                        <div class="social-info-back social-small-rss-hover">
                            <a href="http://www.unlv.edu/directories/socialmedia/rss"></a>
                        </div>	
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>