<div class="features">
<h2 class="fa"><span><?php echo sprintf($this->translate($this->title)) ?></span></h2>
<p><?php echo sprintf($this->translate($this->content)) ?></p>
       
<div class="row">
    
        
        <div class="well span3">
         <a href="<?= $this->url('applications') ?>">
            <div class="centered">
                <i class="fa fa-home fa-5x"></i>
                <h3 class="title"><?= $this->translate($this->app1) ?></h3>
            </div>
        </a>
        </div>
        
        <div class="well span3">
        <a href="<?= strtolower($this->translate($this->app2)) ?>">
            <div class="centered">
                <i class="fa fa-trophy fa-5x" ></i>
                <h3 class="title"><?= $this->translate($this->app2) ?></h3>
            </div>
        </a>
        </div>
        
        <div class="well span3">
        <a href="<?= strtolower($this->translate($this->app3)) ?>">
            <div class="centered">
                <i class="fa fa-list-alt fa-5x" ></i>
                <h3 class="title"><?= $this->translate($this->app3) ?></h3>
            </div>
        </a>
        </div>
        
        <div class="well span3">
        <a href="<?= strtolower($this->translate($this->app4)) ?>">
            <div class="centered">
                <i class="fa fa-list-alt fa-5x" ></i>
                <h3 class="title"><?= $this->translate($this->app4) ?></h3>
            </div>
        </a>
        </div>         
</div>
</div>