<div class="features">
<h2 class="fa"><span><?php echo sprintf($this->translate($this->title)) ?></span></h2>
<? if($this->description): ?>
    <p><? echo sprintf($this->translate($this->description)) ?></p>
<?  endif; ?>
<div class="row">    	
    	<?php 
        if(is_array($this->apps)): 
        foreach ($this->apps as $item):
        ?>
        <div class="well span3">
        <a href="<?= strtolower($this->translate($item['route'])) ?>">
            <div class="centered">
                <i data-prefix="glyphicons" class="fa fa-5x <?= (isset($item['icon']) ? $item['icon'] : '') ?>" ></i>
                <h3 class="title"><?= $this->translate($item['label']) ?></h3>
            </div>
        </a>
        </div>
        <?php endforeach; endif; ?>        
</div>

</div>